name: app_icon_badger
description: Plugin to update the app badge on the launcher (both for Android and iOS)

version: 1.0.0

homepage: https://github.com/TushA55/app_icon_badger

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.app_icon_badger
        pluginClass: AppIconBadgerPlugin
      ios:
        pluginClass: AppIconBadgerPlugin

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"